### ISSUE TITLE
postgresql 10 support

### ISSUE THREAD

**Issue by adampopkiewicz** [ClearcodeHQ/pytest-postgresql#103]
### What action do you want to perform
I've run tests on 9.6 successfully. upgraded version to 10, re-run tests.

### What are the results
test crashes at pg version check in executor.py, no test relying on db connection performs.

### What are the expected results
tests running as in 9.6

### workaround/potential fix
Now, my workaround is to change version regex to account for that extra digit
`PostgreSQLExecutor::version` - I've added extra `\d?`

I haven't noticed any issues so far, as I'm not aware of any backwards incompatible changes in 10.0. yet I'm not sure if it's forward compatible just like that, as my test suite is rather small, and doesn't span all pg features.

**Comment by fizyk** [comment]
@adampopkiewicz Could you check the #104 if ot works for you? or if the version strings in tests are correct?

**Comment by adampopkiewicz** [comment]
thank you! works perfectly

**Comment by fizyk** [comment]
okay, please use version 1.3.2 :)
