### ISSUE TITLE
Issue stopping postgresql during teardown

### ISSUE THREAD

**Issue by awiddersheim** [ClearcodeHQ/pytest-postgresql#126]
After updating to `1.3.4` of this package I started having issues running things on Mac OSX. Looks like the issue is tied to https://github.com/ClearcodeHQ/pytest-postgresql/commit/f224d935e61192c888a6c24bddf02d6b7e7cdf1b. Specifically, the `super(PostgreSQLExecutor, self).stop()` addition. Haven't tried other platforms. I'm also not running as `root` when performing my tests.

Here is a snippet from the traceback when things go wrong:

```
        try:
>           os.killpg(self.process.pid, sig)
E           PermissionError: [Errno 1] Operation not permitted

.tox/py36/lib/python3.6/site-packages/mirakuru/base.py:266: PermissionError
```

Putting a guard around that line seems to help:

```
        if self.running():
            super(PostgreSQLExecutor, self).stop()
```

This _seems_ okay though it does go against the "ask for forgiveness" approach. Not sure if something should really be done in the `mirakuru` library instead. Thanks!

**Comment by autogestion** [comment]
could you give more details on what should be edited to avoid PermissionError on mac

**Comment by fizyk** [comment]
@awiddersheim @autogestion please make sure you've updated mirakuru to 1.0.0 as this should be handled correctly now.
