### ISSUE TITLE
OSX bug introduced in v1.3.4

### ISSUE THREAD

**Issue by ahgnaw** [ClearcodeHQ/pytest-postgresql#127]
Calling `killpg` on a zombie pid on OSX raises `OSError: [Errno 1] Operation not permitted`. In commit f224d935e61192c888a6c24bddf02d6b7e7cdf1b, the line https://github.com/ClearcodeHQ/mirakuru/blob/master/src/mirakuru/base.py#L274 is raising that error when called.

One solution is to use `os.kill` in mirakuru instead.

**Comment by ahgnaw** [comment]
https://github.com/ClearcodeHQ/mirakuru/pull/222

**Comment by fizyk** [comment]
this should be handled properly now by mirakuru 1.0.0
