### ISSUE TITLE
Unable to specify `options` kwarg to underlying psycopg2.connect()

### ISSUE THREAD

**Issue by nackjicholson** [ClearcodeHQ/pytest-postgresql#145]
### What action do you want to perform

I would like to specify options as specified in [33.1 Database Control Functions](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS) as well as in [psycopg2.connect](http://initd.org/psycopg/docs/module.html#psycopg2.connect).

Basically I want to set the `search_path=myschema`.

I think I could also get around this by setting an environment variable of `PGOPTIONS` if I really have to.

### What are the results

Write now the results are, I can't use this project to run my postgresql tests because I get errors due to tables not being found.

I have my tables defined in a schema:

`CREATE SCHEMA myschema;`

But in my app I use the `options='-c search_path=myschema'` to automatically make that the default so that in all my queries I don't have to write `select * from myschema.foo;`. I can write `select * from foo;`.

I need to do the same thing for my psycopg2 connection when it's under test.

### What are the expected results

To be able to send an `options` option through the `pytest.ini` or as a command line option, or as an option to the `postgresql_proc` factory.

### PR

I'll have a PR up shortly that adds that option.

### Workarounds

Somehow get my tables to just build in the `public` schema when I'm testing. (I'm using my same migration scripts for production to build my database under test)

Environment variable everywhere I run tests `PGOPTIONS="-c search_path=myschema"`

**Comment by nackjicholson** [comment]
I ultimately worked around my problem by essentially recreating what your plugin does with my own fixture.

```python
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT


@pytest.fixture
def pgconn(postgresql_proc, request):
    """
    Runs our sqitch migration on the test database
    and inserts test data into it before returning postgres connection.
    """
    pg_host = postgresql_proc.host
    pg_port = postgresql_proc.port
    pg_user = postgresql_proc.user
    pg_db = 'tests'

    with psycopg2.connect(user=pg_user, host=pg_host, port=pg_port) as upconn:
        upconn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
        with upconn.cursor() as cur:
            cur.execute(f'create database {pg_db};')

    pgconn = psycopg2.connect(
        host=pg_host,
        port=pg_port,
        user=pg_user,
        dbname=pg_db,
        options='-c search_path=source_meta'
    )

    with pgconn:
        with pgconn.cursor() as cur:
            for sql_script in get_sql_scripts():
                cur.execute(sql_script)
    pgconn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)

    def drop_db():
        pgconn.close()
        with psycopg2.connect(user=pg_user, host=pg_host, port=pg_port) as downconn:
            downconn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
            with downconn.cursor() as downcur:
                # We cannot drop the database while there are connections to it, so we
                # terminate all connections first while not allowing new connections.
                if float(postgresql_proc.version) >= 9.2:
                    pid_column = 'pid'
                else:
                    pid_column = 'procpid'
                downcur.execute("""
                    update pg_database
                       set datallowconn=false
                     where datname = %s;
                """, (pg_db,))
                downcur.execute(
                    f'SELECT pg_terminate_backend(pg_stat_activity.{pid_column})'
                    'FROM pg_stat_activity WHERE pg_stat_activity.datname = %s;',
                    (pg_db,))
                downcur.execute(f'drop database if exists {pg_db};')

    request.addfinalizer(drop_db)

    return pgconn
```

I don't know what there is to be learned here, but if you have any insights into how to make this project better from what I encountered here, I hope it helps.

**Comment by fizyk** [comment]
I wonder if specific search_path wouldn't do the trick for you. And appropriate modification to postgresql fixture factory https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/factories.py#L241 ?
