### ISSUE TITLE
How can I have two connections to the tests database?

### ISSUE THREAD

**Issue by nackjicholson** [ClearcodeHQ/pytest-postgresql#151]
### What action do you want to perform

I have a test of a flask server which is injected with the postgresql connnection object. Once it finishes serving a request, it closes that connection.

After making a request to create objects in my test database I would like to open a second connection to verify the objects are in the database. I can't seem to get this to work with the `factories`.

**Comment by fizyk** [comment]
Could you show some snippet? If I test an app, I usually let the app connect by itself, using the fixture connection to prepare test data or check, if the code modified the data in a table as intended.

**Comment by nackjicholson** [comment]
Sure.

In my _conftest.py_

```python
@pytest.fixture
def pgconn(postgresql):
    """Runs the sqitch plan and loads seed data before returning db connection.
    """
    with postgresql:
        # Setup the database from the migration scripts
        with postgresql.cursor() as cur:
            for sql in get_migration_scripts():
                cur.execute(sql)

        # Loads data from csvs into the test dbs tables.
        for table, path, columns in SQL_FIXTURES:
            with postgresql.cursor() as cur:
                with path.open() as fp:
                    cur.copy_from(fp, table, columns=columns)

    return postgresql

@pytest.fixture
def client(pgconn):
    """Flask testing client with test database connections pushed to app context."""
    app = create_app(TestConfiguration)

    def handler(_sender, **_kwargs):
        g.pgconn = pgconn

    with appcontext_pushed.connected_to(handler, app):
        yield app.test_client()
```

So that is how I have my flask app setup. It holds that connection on it's internal application context, and when a request is finished it closes the connection.

So in my _test_something.py_ I am trying to do something like this.

```python
def test_something(client, postgresql)
data = json.dumps({'foo': 'bar'})
res = client.post('/foo', data=data, content_type='multipart/form-data')

actual = res.get_json()
expected = {'foo_id': 1}
assert actual == expected

with postgresql.cursor() as cur:
    cur.execute("""
        select some_field from foo_table where foo_id = 1
    """)
    my_updated_db_stuff = cur.fetchone()[0]
    assert my_updated_db_stuff == {'some_field': 'data_that_got_put_in_db'}
```

But I get an error saying the postgresql connection has already been closed (since it was closed by the application at the end of the request). I can't check the contents of the database after the request has ended.

**Comment by fizyk** [comment]
What are you using underneath to connect to database? sqlalchemy?
That's one of the older pieces of code I use: https://github.com/fizyk/pyramid_fullauth/blob/master/tests/conftest.py#L39

Basically, all request/view should do is to commit transaction, close cursor, not a connection. Connection should stay until it breaks or application ends (till the end of the client fixture). A connection pool?

**Comment by nackjicholson** [comment]
From above, basically what I changed about my setup is to not use:

```python
def handler(_sender, **_kwargs):
        g.pgconn = pgconn

with appcontext_pushed.connected_to(handler, app):
        yield app.test_client()
```

Instead, as @fizyk suggested I'm letting the server connect itself. In my case this meant needing to configure my app to connect to the 'tests' database provided by this module.

To do this I leveraged the [get_dsn_parameters](http://initd.org/psycopg/docs/connection.html#connection.get_dsn_parameters) method available on the pyscopg2 connection to use the fixture connnection details in my app as well.

My `client` fixture became:

```python
@pytest.fixture
def client(pgconn):
    """Flask testing client with test database connections"""
    pg_params = pgconn.get_dsn_parameters()

    class TestConfiguration:
        TESTING = True
        POSTGRES_DB_SERVER = pg_params['host']
        POSTGRES_DB_PORT = pg_params['port']
        POSTGRES_DB_NAME = pg_params['dbname']
        POSTGRES_DB_USERNAME = pg_params['user']
        POSTGRES_DB_PASSWORD = None

    app = create_app(TestConfiguration)

    yield app.test_client()
```

Now I can use the `pgconn` fixture at any point in my test functions (including after requests!).
