### ISSUE TITLE
Database creation fails when name contains hyphen

### ISSUE THREAD

**Issue by jamescooke** [ClearcodeHQ/pytest-postgresql#195]
### What action do you want to perform

Create a database called "qp-test"

### What are the results

Failure with:

```
> cur.execute('CREATE DATABASE {0};'.format(db_name))
E psycopg2.ProgrammingError: syntax error at or near "-"
E LINE 1: CREATE DATABASE qp-test;
```

### What are the expected results

Database should be created.

**Comment by fizyk** [comment]
@jamescooke please check v1.4.1
