### ISSUE TITLE
Question: Is a postgres installation needed for pytest-postgresql?

### ISSUE THREAD

**Issue by chr1st1ank** [ClearcodeHQ/pytest-postgresql#221]
It doesn't get that clear from the setup instructions:
Do I need to install posgres (server) separately in order to use pytest-postgresql?

When I found this pytest extension I first assumed that it only mocks a connection, but it seems it creates a real test database on a real local postgres server.

Could you please clarify this?

**Comment by fizyk** [comment]
Yes, you need to have postgresql installed. However the fixture takes care of starting, setting up database and keeping it clean between tests so no changes will leak between tests.

See https://github.com/ClearcodeHQ/pytest-postgresql#what-is-this and bit lower description of both fixtures.

**Comment by chr1st1ank** [comment]
Ok, thanks.
