### ISSUE TITLE
AttributeError: 'function' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/pytest-postgresql#24]
_From @tommagic on October 27, 2016 12:14_

I follow the example here - http://pytest-dbfixtures.readthedocs.io/en/latest/howtouse.html for postgres - 

```
from pytest_dbfixtures import factories

postgresql_proc2 = factories.postgresql_proc(port=9876)
postgresql2 = factories.postgresql('postgresql_proc2')
cur = postgresql2.cursor()
```

I get the following error - 
`AttributeError: 'function' object has no attribute 'cursor'`

My version is - pytest-dbfixtures==0.16.0 and psycopg2==2.6.2, postgres 9.6 running locally.
What do I do wrong?

_Copied from original issue: ClearcodeHQ/pytest-dbfixtures#208_

**Comment by fizyk** [comment]
@tommagic you'd have to change it a bit:

cur = postgresql2().cursor()

And event then, it's a pytest fixture, that depends on other pytest fixture.

```
def test_two_postgreses(postgresql, postgresql2):
    cur = postgresql.cursor()
```

**Comment by brendanashworth** [comment]
Using the code in this comment was really helpful for me as I fixed this problem: https://github.com/ClearcodeHQ/pytest-postgresql/issues/454#issuecomment-899928019
