### ISSUE TITLE
Support transactional testing for fast tests with shared setup

### ISSUE THREAD

**Issue by connorbrinton** [ClearcodeHQ/pytest-postgresql#246]
When writing tests, developers need to ensure that tests are both isolated from each other and fast. These two goals come into conflict when tests require interacting with a database, since tests typically require the database to be in a certain state. This state may include:
* Database schema
* Specific data in the database

Bringing the database to the required state from scratch takes time. Additionally, to ensure isolation, the database is typically completely wiped between each test. This means that every test needs to bring the database to a specific state, even if some part of that state is shared with other tests.

An alternative to resetting the database between each test is using the built-in isolation capabilities of the database to prevent tests from affecting each other. This is called "transactional testing", and often uses PostgreSQL-specific features such as `SAVEPOINT`s to roll-back changes made by a test before the next test runs, without completely resetting the database.

One example of a library implementing this approach is [pytest-flask-sqlalchemy](https://github.com/jeancochrane/pytest-flask-sqlalchemy). However, that library's use case is fairly narrowly defined to only projects using both Flask and SQLAlchemy.

I think it would be really awesome if `pytest-postgresql` were to support transactional testing use cases (perhaps using scoped fixtures or fixture decorators). Do you think this would be within the scope of `pytest-postgresql`, or would this be better-suited as a separate library?

**Comment by fizyk** [comment]
I think that would be something worth considering.

As I'm not sure when I'll find the time to work on this, but you're welcome to create a pull request.
One thing to consider would be to put documentation warnings that the same connection has to be sued throughout the test suite as any new connection code will make would be outside of the transaction

**Comment by efagerberg** [comment]
I think having a transactional fixture is preferred. In my case I have noticed that sometimes the postgres server fails to start up leading to flakey test suits, just having one db that is more global in pytest would reduce the setup time for each test and hopefully make the test suite less brittle.

**Comment by fizyk** [comment]
Addressed by #407 / #393
