### ISSUE TITLE
Regression with drop_postgresql_database

### ISSUE THREAD

**Issue by di** [ClearcodeHQ/pytest-postgresql#252]
Since `pytest-postgresql==2.1.0` we've gotten test failures indicating that our test database is not being properly dropped.

In #227, it looks like there is a copy/paste error, and `drop_postgresql_database` is calling `DatabaseJanitor.init()` instead of `DatabaseJanitor.drop()`:

https://github.com/ClearcodeHQ/pytest-postgresql/blob/94c5c9b7ba1a8dbd1f80827a992eb43492314639/src/pytest_postgresql/factories.py#L109-L124

**Comment by fizyk** [comment]
see version 2.2.1 Sorry for the issues
