### ISSUE TITLE
perform test queries to check database info

### ISSUE THREAD

**Issue by ELGUMOS1** [ClearcodeHQ/pytest-postgresql#263]
### What action do you want to perform
Hey I was wondering if there is a way to perform pytests about the data inside the database. 
I mean to query data from the database and do a simple test all in a docker instance. I perform a script to fill the database with some info, then i want to test if the info match some numbers everything in a docker

### What are the expected results

**Comment by fizyk** [comment]
@ELGUMOS1 do you want to checkw hether the script adds the information to docker instance correctly, or whether the docker isntance is constructed correctly?
