### ISSUE TITLE
DatabaseJanitor.init() fails if username doesn't match an existing db name

### ISSUE THREAD

**Issue by ashokdelphia** [ClearcodeHQ/pytest-postgresql#279]
### What action do you want to perform

I have a service, 'something-backend', which has an existing dev database called `something_backend` with the database user `something-backend`. For tests, I'd like to use `pytest-postgresql` to make a throwaway database called `something_backend_test`, using the same database user.

So I want to initialize a new database where the username does not match an existing database, e.g.

```
from pytest_postgresql.factories import init_postgresql_database

user = 'something-backend'
host = 'db'
port = '5432'
db_name = 'something_backend_test'
init_postgresql_database(user, host, port, db_name)
```
or similarly calling the non-deprecated version:
```
DatabaseJanitor(user, host, port, db_name, 0.0).init()
```

### What are the results

    psycopg2.OperationalError: FATAL:  database "something-backend" does not exist

If I rename the user to `something_backend`, and have an existing database called that, then the code above will make the `something_backend_test` database.

### What are the expected results

The database is successfully created.

I believe this is because the [`psycopg2.connect()` call in Janitor](https://github.com/ClearcodeHQ/pytest-postgresql/blob/255681b/src/pytest_postgresql/janitor.py#L79) is only passing the user, host and port, so Postgres is defaulting to a database name that matches the user's name.

I think it would be safe to pass `dbname='postgres'` here, and if I make that change locally, everything appears to work as expected.

**Comment by fizyk** [comment]
> I believe this is because the psycopg2.connect() call in Janitor is only passing the user, host and port, so Postgres is defaulting to a database name that matches the user's name.

never thought about this, but it makes sense actually, and the default user in pytest-postgresql is actually a `postgres`, so unless you change that, you're okay. And I don't think anyone changes that user ;)
