### ISSUE TITLE
C.UTF-8 locale are not supported on Centos 7

### ISSUE THREAD

**Issue by arnaudsjs** [ClearcodeHQ/pytest-postgresql#338]
### What action do you want to perform

Use `pytest-postgresql` version 2.5.1 on Centos 7.

### What are the results

Our test suite fails with the following message when `pytest-postgresql` executes the `pg_ctl initdb` command.

```
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
initdb: invalid locale settings; check LANG and LC_* environment variables
pg_ctl: database system initialization failed
```

### What are the expected results

It would be nice if `pytest-postgresql` would allow the locale `en_US.UTF-8`, since `C.UTF-8` is not supported on Centos 7 and no support will be added in the future.

**Comment by fizyk** [comment]
related: #339

**Comment by evoludigit** [comment]
same problem here on Archlinux.

It seems the C.UTF-8 locale is a Debian thing:
https://github.com/commercialhaskell/stack/issues/856

**Comment by fizyk** [comment]
please check v2.5.2 version
