### ISSUE TITLE
Postgres status checks depend on pg_ctl logs language

### ISSUE THREAD

**Issue by zoowirt** [ClearcodeHQ/pytest-postgresql#339]
### What action do you want to perform
If pg_ctl does not write logs in english, two status checks do not work:
https://github.com/ClearcodeHQ/pytest-postgresql/blob/fbced464ca645840683804d0ac30048df6576d08/src/pytest_postgresql/executor.py#L181
https://github.com/ClearcodeHQ/pytest-postgresql/blob/fbced464ca645840683804d0ac30048df6576d08/src/pytest_postgresql/executor.py#L216

For instance, on my system the logs are in german. In this case `database system is ready to accept connections` is equivalent to `Datenbanksystem ist bereit, um Verbindungen anzunehmen`. As as result, the postgres is never recognized as running, even though it is.

It would be nice if both status checks were independent of the language in the pg_ctl logs, such that the module works for any pg_ctl language. A possible solution would be to use `subprocess.getstatusoutput` instead of reading the log files and check for `status == 0` (running) or `status == 3` (not running), as described here: https://www.postgresql.org/docs/current/app-pg-ctl.html

**Comment by fizyk** [comment]
@zoowirt out of curiosity what version do you use? 

I thought that setting up the locales and env vars would handle the case

**Comment by zoowirt** [comment]
I use `pytest-postgresql==2.5.1` and PostgreSQL 11.5

**Comment by fizyk** [comment]
another question, would it be better on 2.5.0? I just wonder if the 2.5.1 broke it, or it didn't worked correctly from the beginning.

**Comment by zoowirt** [comment]
Same problem in 2.5.0, for the same reason

**Comment by fizyk** [comment]
@zoowirt thank you for checking. I reviewed your pull request and made some notes.
