### ISSUE TITLE
Add option for username to run `pg_ctl` commands as

### ISSUE THREAD

**Issue by b0urb0n** [ClearcodeHQ/pytest-postgresql#341]
### What action do you want to perform
I would like to be able to use this test library in a Docker container as part of a CI/CD pipeline

### What are the results
The fixture raised an error because PSQL doesn't want to run as root (the default in a Docker container):
```
E               subprocess.CalledProcessError: Command '['/usr/lib/postgresql/11/bin/pg_ctl', 'initdb', '--pgdata', '/tmp/postgresqldata.16728', '-o', '--username=postgres --auth=trust']' returned non-zero exit status 1.
/usr/local/lib/python3.7/subprocess.py:512: CalledProcessError
---------------------------- Captured stderr setup -----------------------------
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
________________________ ERROR at setup of test_sample _________________________
```

### What are the expected results
For the fixture to be configured to (create and) use a user that is not root.  As you're using `subprocess.check_output`, you could simply (create a user and) add the `user` kwarg which gets proxied to `subprocess.Popen`

**Comment by fizyk** [comment]
Isn't that rather a dockerfile configuration? You'd need to create a user that's not a root and run commands and entry points as that particular user?

**Comment by b0urb0n** [comment]
It's somewhat uncommon in my experience to do it that way but I don't see why it wouldn't work.  At the end of the day, I don't think user management is within scope for this pytest-plugin.  My solution was to use the Janitor but I thought it would've been nice to be able to run everything in a self-contained container.

For anyone else who finds this, @fizyk is talking about the [`USER`](https://docs.docker.com/engine/reference/builder/#user) instruction that can be set in the Dockerfile.

**Comment by risoms** [comment]
@b0urb0n I could use the solution here as well.
