### ISSUE TITLE
Problem calling pg_ctl with "--auth=trust"

### ISSUE THREAD

**Issue by BrunoCoimbra** [ClearcodeHQ/pytest-postgresql#343]
Hello,

I noticed the changes in 2.5.1 seem to break pytest_postgresql fixtures.
The problem happens when pg_ctl tries to call initdb adding the "--auth=trust" parameter:

```
subprocess.CalledProcessError: Command '['/usr/bin/pg_ctl', 'initdb', '--pgdata', '/tmp/postgresqldata.15455', '-o', '--username=postgres --auth=trust']' returned non-zero exit status 1.
```

Executing the same command directly on terminal I get:

```
/usr/bin/pg_ctl initdb --pgdata /tmp/postgresqldata.15455 -o --username=postgres --auth=trust
/usr/bin/pg_ctl: unrecognized option '--auth=trust'
Try "pg_ctl --help" for more information.
```

Are there new configuration requirements I'm missing, or is it an actual bug?

Thanks,
Bruno

**Comment by fizyk** [comment]
Could you check v2.5.2 if it still occurs?
What system are you on? And did that worked for you before?

**Comment by BrunoCoimbra** [comment]
Yes, the problem still occurs on v2.5.2. I'm using Postgresql 11 on Scientific Linux 7.
Thanks for looking into it.

**Comment by michael-burt** [comment]
I am still experiencing this issue in v2.5.2.

```
$ python
Python 3.8.6 (default, Oct 13 2020, 20:49:19)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest_postgresql
>>> pytest_postgresql.__version__
'2.5.2'
>>> exit()
$ /usr/lib/postgresql/11/bin/pg_ctl initdb --pgdata /tmp/postgresqldata.25110 -o --username=postgres --auth=trust
/usr/lib/postgresql/11/bin/pg_ctl: unrecognized option '--auth=trust'
Try "pg_ctl --help" for more information.
$ /usr/lib/postgresql/11/bin/pg_ctl --version
pg_ctl (PostgreSQL) 11.9 (Debian 11.9-0+deb10u1)
```

**Comment by fizyk** [comment]
If anyone is experiencing this issue, I'll accept tested solution, review pull request, but actually have to time to actively work on it.

**Comment by davidlee-ca** [comment]
I ran into this problem on Mac. 

Turns out it was a stray copy of `libpq` that didn't support the `--auth` flag. My solution: remove libpq, remove and reinstall postgres.

**Comment by blelia** [comment]
I am using the same version, and I have the same problem, reinstalling did not solve the problem.  
Any ideas?
```
> pg_ctl --version           
pg_ctl (PostgreSQL) 16.1 (Homebrew)
> python3.11 -m pip show pytest-postgresql
Name: pytest-postgresql
Version: 5.0.0
Summary: Postgresql fixtures and fixture factories for Pytest.
Home-page: 
Author: 
Author-email: Grzegorz Śliwiński <fizyk+pypi@fizyk.dev>
License: 
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: mirakuru, port-for, psycopg, pytest, setuptools
Required-by: 
> pg_ctl initdb --pgdata /XXX/YYY/ZZZ/pytest-postgresql-postgresql_proc0/data-65432 -o --username=myusername --auth=trust                
pg_ctl: unrecognized option `--auth=trust'
Try "pg_ctl --help" for more information.
```

**Comment by nachonavarro** [comment]
Same here, auth is not recognized

**Comment by realDragonium** [comment]
I experienced the same issues, the `subprocess.CalledProcessError: Command` error, in my main terminal application, but in some other terminals it worked for some reason. 

After a bit of digging, it got my tests working again after adding `LANG=en_US.UTF-8` in front of my pytest run command. 

Adding this env variable in front of the actual command being ran doesn't resolve the `pg_ctl: unrecognised option `--auth=trust'` issue. 

If you find this comment, I hope this might be useful.

**Comment by fizyk** [comment]
Okay, we use envvars for main process start, but here https://github.com/ClearcodeHQ/pytest-postgresql/blob/main/pytest_postgresql/executor.py#L180 it's not used, @realDragonium have you tried it there? (line 180 or line 184?

**Comment by fizyk** [comment]
okay, but the first is only in logs and the whole test suite runs fine, right?

Would you be able to modify your copy of pytest-postgresql with such diff and see the results?

``` diff
diff --git a/pytest_postgresql/executor.py b/pytest_postgresql/executor.py
index 2579749..d61acc1 100644
--- a/pytest_postgresql/executor.py
+++ b/pytest_postgresql/executor.py
@@ -177,11 +177,11 @@ def init_directory(self) -> None:
                 password_file.write(password)
                 password_file.flush()
                 init_directory += ["-o", " ".join(options)]
-                subprocess.check_output(init_directory)
+                subprocess.check_output(init_directory, env=self._envvars)
         else:
             options += ["--auth=trust"]
             init_directory += ["-o", " ".join(options)]
-            subprocess.check_output(init_directory)
+            subprocess.check_output(init_directory, env=self._envvars)
 
         self._directory_initialised = True
```

**Comment by realDragonium** [comment]
> okay, but the first is only in logs and the whole test suite runs fine, right?

Yes it does


> Would you be able to modify your copy of pytest-postgresql with such diff and see the results?

Yes, it works with the provided modification. (And it stops working when i remove the change) 

Awesome!

**Comment by fizyk** [comment]
Okay, got pull request, now to think a bit how to test it.
