### ISSUE TITLE
documention request: example for postgresql_nooproc usage

### ISSUE THREAD

**Issue by lioramilbaum** [ClearcodeHQ/pytest-postgresql#348]
postgresql container spinned with docker-compose.
Invoking query and asserting the result

Didn't find a complete example/code snippet which does something similar.
Would appreciate a code example.

**Comment by fizyk** [comment]
the warehouse ( https://github.com/pypa/warehouse ) project uses this kid of setup - at least used, last time I checked. It wasn't full use, but they used DatabaseJanitor part to clean the database.

Basically, whther you use docker-compose, or just run postgres through docker, you need to run it before tests and make sure you pass connection configuration to the pytest.

**Comment by fizyk** [comment]
Not sure when I'll find the time, but eventually I'll think of something to write

**Comment by bkircher** [comment]
Hey there. Yes https://github.com/pypa/warehouse is a good starting point.

I could also write something up that uses pytest fixture with 
```
from pytest_postgresql.factories import DatabaseJanitor, get_config
```
for testing a Flask app both, locally and in a GitLab pipeline.

Any particular good place I would put this in?

**Comment by fizyk** [comment]
@bkircher Sorry for late response. A section "examples" at the end of readme maybe?

**Comment by jschaeff** [comment]
Hi,
I found a typo in the doc.
It says `postgresql_nooproc` everywhere, but it's actualy `postgresql_noproc` in the code.

**Comment by fizyk** [comment]
@jschaeff if you'd have a bit of time to fix it I'd gladly merge it

**Comment by fizyk** [comment]
Please check readme's example section now

**Comment by tl24** [comment]
FYI, this turned out to be a breaking change between 2.x and 3.0

**Comment by fizyk** [comment]
@tl24 the fixture name? Sorry, I must have overlook the lack of note, when that change got introduces. Could you create a pr adding that to changes? For the future?

**Comment by tl24** [comment]
Ok, I added the pull request #421
