### ISSUE TITLE
Unicode charmap issues.

### ISSUE THREAD

**Issue by ndion617** [ClearcodeHQ/pytest-postgresql#360]
### What action do you want to perform
I am unsure if this issue is directly related to this package or something used by this package but I am trying to create a fixture loading in a pre-exsisting SQL file with some data including the string '196‐Channel' which has a unicode dash 0xe28090 inside it . Also our data has these quotes: ” 0xe2809d that also cannot be decoded. These values are apart of strings that belong to a text field of our database and correspond to data cases we have encountered. 

### What are the results
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 145: character maps to <undefined>

### What are the expected results
Expecting the SQL file to load in and populate the test postgresql instance.

**Comment by fizyk** [comment]
Could be connection parameters missing, or could be some general configuration error issues. I'd appreciate some help here though. (Preferably start with a test)

**Comment by ndion617** [comment]
Here is the area things are falling and an included test case, I also tried with postgresql_proc instead of the noproc. Hopefully this can help

`postgresql_my_proc = factories.postgresql_noproc() 
tempPostgresql = factories.postgresql('postgresql_my_proc',load=['testExample.sql']`

Also the testExample with the erroring issues:
[testExample.zip](https://github.com/ClearcodeHQ/pytest-postgresql/files/5875267/testExample.zip)

I was also able to load this by giving the open command in the factories.py line 267 the file encoding utf8 option

`            if pg_load:
                for filename in pg_load:
                    with open(filename, 'r', encoding = 'utf8') as _fd:
                        with db_connection.cursor() as cur:
                            cur.execute(_fd.read())`

**Comment by fizyk** [comment]
@ndion617 sorry for late response, what does the `locale.getpreferredencoding()` output returns for you? looking at the encoding description for open, that issue might be really platform dependend. And given changed architecture of the solution at the moment, the final solution might be easier or harder ;)
