### ISSUE TITLE
Help me use this library

### ISSUE THREAD

**Issue by jschaeff** [ClearcodeHQ/pytest-postgresql#377]
### I want to use pytest-postgresql to test my application

This is my pytest file:

```python
import pytest
from pytest_postgresql import factories
from webservice import app

postgresql_my_proc = factories.postgresql_noproc(host="localhost", port="5432", password="password")
postgres_with_schema = factories.postgresql('postgresql_my_proc', db_name="test", load=['tests/eidastats_schema.sql'])

def test_postgres_1(postgres_with_schema):
    """
    Check main postgres fixture
    """
    with postgres_with_schema.cursor() as cur:
      cur.execute("select * from tokens")
      print(cur.fetchall())
```
My postgresql instance is running as a container.

### What are the results

Pytest run says:

```
================================================= short test summary info 
FAILED tests/test_app.py::test_postgres_1 - psycopg2.errors.UndefinedTable: relation "tokens" does not exist
```

The schema seems to be applied because when I modify it to insert an obvious syntax error, the pytest report shows it as expected.

I don't get what I am doing wrong. Can you help ?

**Comment by fizyk** [comment]
could you post also the sql file? or a sample one?

**Comment by jschaeff** [comment]
Sure, you can see it here : https://github.com/EIDA/eida-statistics/blob/main/webservice/tests/eidastats_schema.sql

Thank you !

**Comment by fizyk** [comment]
@jschaeff I managed to reproduce the error on the CI here. Please check the related PR, unless you've found a solution and can suggest something there to introduce the fix

**Comment by fizyk** [comment]
@jschaeff either remove the search_path from the script `SELECT pg_catalog.set_config('search_path', '', false);` or query for `public.tokens`.

See related pull request.

**Comment by fizyk** [comment]
https://www.postgresql.org/docs/13/ddl-schemas.html#DDL-SCHEMAS-PATH
