### ISSUE TITLE
How to implement Postgres extension ?

### ISSUE THREAD

**Issue by evoludigit** [ClearcodeHQ/pytest-postgresql#381]
Hello,

First of all, thanks for this great library.

Is it possible to install a Postgres extension in an inmemory database ?

### What I am trying to do

I am trying like to activate the LTREE extension in an on memory database, so as to store materialized path information (hierarchy information, where all the ancestors are stored as part of the record).

Code used to set up the inmemory database:
```
socket_dir = tempfile.TemporaryDirectory()
postgresql_my_proc = factories.postgresql_proc(
    port=None,
    unixsocketdir=socket_dir.name,
)
postgresql_my = factories.postgresql("postgresql_my_proc")


@pytest.fixture
def in_memory_db(postgresql_my):
    def db_creator():
        return postgresql_my.cursor().connection

    engine = create_engine("postgresql+psycopg2://", creator=db_creator)
    metadata.create_all(engine)
    return engine


@pytest.fixture
def session(in_memory_db):
    start_mappers()
    Session = sessionmaker(bind=in_memory_db)
    session = Session()
    # session.execute("CREATE EXTENSION ltree;")
    yield session
    clear_mappers()
```

### Results

- Without the instruction `CREATE EXTENSION ltree;`, I get the following error:
`psycopg2.errors.UndefinedObject: type "ltree" does not exist`

- With the instruction `session.execute("CREATE EXTENSION LTREE")`, I get this error:

```
E       sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "CREATE EXTENSION"
E       LINE 1: CREATE EXTENSION ltree;
E               ^
E
E       [SQL: CREATE EXTENSION ltree;]
E       (Background on this error at: http://sqlalche.me/e/13/f405)

```

### What are the expected results

Being able to use LTree type in the inmemory database.

Thanks a lot !

**Comment by fizyk** [comment]
@evoludigit it should be generally possible. You should be able to perform any action you'd do normally with postgres granted it does not require start configuration in the begining.

It'd take some time for me to work on it, and if you've got any pieces, you could contribute, please do so.

But for starters, have you tried to create extensions directly on the postgresql_my client? Something in the lines:

``` python
with postgresql_my.cursor().connection as c:
    c.execute("CREATE EXTENSION postgis;")
```

**Comment by evoludigit** [comment]
Hello,

thanks a lot for your reply.

Your suggestion did not work for me:

```
    def db_creator():
        with postgresql_my.cursor().connection as c:
>           c.execute("CREATE EXTENSION IF NOT EXISTS ltree;")
E           AttributeError: 'psycopg2.extensions.connection' object has no attribute 'execute'
```

however it pointed me to the right direction, and I could create extension by running pure SQL on the engine rather than on the session :

```
socket_dir = tempfile.TemporaryDirectory()
postgresql_my_proc = factories.postgresql_proc(
    port=None,
    unixsocketdir=socket_dir.name,
)
postgresql_my = factories.postgresql("postgresql_my_proc")


@pytest.fixture
def in_memory_db(postgresql_my):
    def db_creator():
        return postgresql_my.cursor().connection

    engine = create_engine("postgresql+psycopg2://", creator=db_creator)
    result = engine.execute(text("CREATE EXTENSION IF NOT EXISTS ltree;").execution_options(autocommit=True))
    metadata.create_all(engine)
    return engine
```

Thanks again.
