### ISSUE TITLE
Flask factory testing

### ISSUE THREAD

**Issue by BorjaEst** [ClearcodeHQ/pytest-postgresql#403]
### What action do you want to perform
Run my tests developed in flask + pytest using pytest-postgresql.
Follow [flask factory conventions](https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/?highlight=config#the-application-factory).
Use the [slqalchemy](https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/) with configuration variable SQLALCHEMY_DATABASE_URI.

### Example
```py
@fixture(scope="session")
def connection(postgresql_proc):
    """Create application for the tests."""
    dbname = "test" # <-- Cannot access a default table for the tests?¿?
    user = postgresql_proc.user
    host = postgresql_proc.host
    port = postgresql_proc.port
    return f'postgresql+psycopg2://{user}:@{host}:{port}/{dbname}'


@fixture(scope="session")
def app(connection):
    """Create application for the tests."""
    return create_app(
        config_object="eosc_perf.settings.TestingConfig",
        SQLALCHEMY_DATABASE_URI=connection)

@fixture
def db(app):
    """Create database for the tests."""
    _db.app = app
    _db.create_all()  # 
    yield _db
    # Explicitly close DB connection
    _db.session.close()
    _db.drop_all()
```

**Comment by BorjaEst** [comment]
For now I am getting:
```py
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "test" does not exist
```
I undestand that **postresql_proc** does not initialise the database inside postgres. What would be the most "common" way to solve this? 
Suggestions?

**Comment by fizyk** [comment]
@BorjaEst change the app fixture to function one. And either use postgresql fixture as dependency, or DatabaseJanitor directly.
You do not want to leak application state between tests anyway.

``` python
@fixture
def app(postgresql, connection):
    """Create application for the tests."""
    return create_app(
        config_object="eosc_perf.settings.TestingConfig",
        SQLALCHEMY_DATABASE_URI=connection)
```

**Comment by BorjaEst** [comment]
@fizyk thanks for the comments. I would rather try to do not create a new "app" for each function, as the more extensions I have the exponentially grow the time for tests. However, the idea of DatabaseJanitor works fine. I somehow was able to achieve what I was looking for with:

```py
from your_app import database  # To patch your app session to enable rollback
from your_app import create_app
from pytest import fixture
from pytest_postgresql.factories import DatabaseJanitor
from sqlalchemy import orm

TEST_DB = 'test_database'  # Database name to create
VERSION = 12.2  # postgresql version number
Session = orm.scoped_session(orm.sessionmaker())

@fixture(scope='session')
def connection(postgresql_proc):
    """Create a temp Postgres database for the tests."""
    USER = postgresql_proc.user
    HOST = postgresql_proc.host
    PORT = postgresql_proc.port
    with DatabaseJanitor(USER, HOST, PORT, TEST_DB, VERSION):
        yield f'postgresql://{USER}:@{HOST}:{PORT}/{TEST_DB}'


@fixture(scope="session")
def app(connection):
    """Create application for the tests."""
    return create_app(
        config_base="eosc_perf.settings.TestingConfig",
        SQLALCHEMY_DATABASE_URI=connection)


@fixture(scope='session')
def db(app):
    """Create database for the tests."""
    database.db.app = app
    Session.configure(bind=database.db.engine)
    database.db.session = Session  # Patch app db session
    database.db.create_all()
    yield database.db
    database.db.drop_all()


@fixture(scope='function')
def session(db):
    """Creates a new database session for a test."""
    session = Session()  # Prepare a new, clean session
    session.begin(nested=True)  # Rollback test commits
    yield session
    session.rollback()  # Discard test changes
    Session.remove()  # Next test gets a new Session()
```

This allows to set the db only 1 time and rollback all the changes at the end of the test.
Hope it might be interesting for other people.

If no more comments I think we can close the issue.

**Comment by fizyk** [comment]
Okay, just be careful of the application state itself (you might want to determine if there are other elements you need to clean up every session).

I recall testing Flask application with several services, different db's several years back, and it wasn't walk in the park 🤔

**Comment by BorjaEst** [comment]
Yes, actually that was a pain as well. That is why it is very important to use **`session.begin(nested=True)`** instead of a simple **`session.begin()`**. That ensures that the state changes done by the application are rolledback as well. 

However, it took me a while to solve it and it is very "sqlalchemy" related, not postgres.
