### ISSUE TITLE
documentation / new user issue: process fixture does not take kwarg 'load'

### ISSUE THREAD

**Issue by sinback** [ClearcodeHQ/pytest-postgresql#449]
I'm reading the [intro documentation on pypi](https://pypi.org/project/pytest-postgresql/):

> The process fixture performs the load once per test session, and loads the data into the template database. Client fixture then creates test database out of the template database each test, which significantly speeds up the tests.

```
postgresql_my_proc = factories.postgresql_proc(
    load=["schemafile.sql", "otherschema.sql", "import.path.to.function", "import.path.to:otherfunction", load_this]
)
```

but when trying to give the `load` keyword to `postgresql_proc`:
```
TypeError: postgresql_proc() got an unexpected keyword argument 'load'
```

it looks like `load` is not a kwarg to the `postgresql_proc()` process-based fixture, only to the `postgresql()` client-based fixture:

```
help(factories.postgresql_proc)
Help on function postgresql_proc in module pytest_postgresql.factories:

postgresql_proc(executable: str = None, host: str = None, port: Union[str, int, Iterable] = -1, user: str = None, password: str = None, options: str = '', startparams: str = None, unixsocketdir: str = None, logs_prefix: str = '') -> Callable[[_pytest.fix
tures.FixtureRequest, _pytest.tmpdir.TempdirFactory], pytest_postgresql.executor.PostgreSQLExecutor]
    Postgresql process factory.

    :param str executable: path to postgresql_ctl
    :param str host: hostname
    :param str|int|tuple|set|list port:
        exact port (e.g. '8000', 8000)
        randomly selected port (None) - any random available port
        -1 - command line or pytest.ini configured port
        [(2000,3000)] or (2000,3000) - random available port from a given range
        [{4002,4003}] or {4002,4003} - random of 4002 or 4003 ports
        [(2000,3000), {4002,4003}] - random of given range and set
    :param str user: postgresql username
    :param str options: Postgresql connection options
    :param str startparams: postgresql starting parameters
    :param str unixsocketdir: directory to create postgresql's unixsockets
    :param str logs_prefix: prefix for log filename
    :rtype: func
    :returns: function which makes a postgresql process
```

So the documentation seems to be out of date or something right now.

Also, if you could let me know the best way to have a pytest-postgresql db running throughout the pytest, that loads my schema file when first created, that would be helpful to me. Should I be using startparams maybe?

**Comment by sinback** [comment]
Agh, nevermind, did not realize the release version I was using was pinned to something out-of-date. Was using 2.5.1, but upgrading to 3.1.1 fixed it. my bad

**Comment by fizyk** [comment]
Glad everything is working :)
