### ISSUE TITLE
Enhancement request / Question: Support for drivers other than psycopg2

### ISSUE THREAD

**Issue by kyri-petrou** [ClearcodeHQ/pytest-postgresql#453]
Apologies if this has been asked before but I couldn't find an issue covering this topic.

Are there any plans to support drivers other than psycopg2? Our team has migrated to using pg8000 due to its integration with awswrangler, and was wondering whether this might be something that's on the roadmap.

Thanks!

**Comment by fizyk** [comment]
@kyri-petrou no, it's not on a roadmap, and have to immediate plans to implement that.
I don't see a reason against, maybe except, maybe that it would be somewhat difficult to support both libraries (although not possible) and the solution could be complicated.... 🤔 

Personally, if you've got code that does something using datawrangler in conjunction with pg8000 I have nothing against using psycopg2 (like here) to prepare the data and then perform checks on the results in the database if there is need. However someone might not like having two postgresql libraries on the CI

**Comment by kyri-petrou** [comment]
@fizyk thanks for the response. Unfortunately using two pg libraries is out of the question at this stage. Will likely end up running an instance of postgres in a docker container locally as part of the test phase.

Thanks once more!
