### ISSUE TITLE
How to reinitialize the db on every test 

### ISSUE THREAD

**Issue by ahahn95** [ClearcodeHQ/pytest-postgresql#454]
### What action do you want to perform
I want a fresh db for every test so that my results are predictable. I am using a noproc fixutre and a postgres db running in a docker container. I tried following [this](https://github.com/ClearcodeHQ/pytest-postgresql#using-a-common-database-initialisation-between-tests) part from the readme, but my function is not getting called. Here is my code, it is very similar to the example.

```
from pytest_postgresql.factories import postgresql, postgresql_noproc
import pytest

def load_database(**kwargs):
    print('hi')


postgresql_noproc = postgresql_noproc(load=[load_database])
postgresql = postgresql("postgresql_noproc", dbname="data_retention")


@pytest.fixture
def get_db(postgresql):
    def conn():
        return postgresql.cursor().connection

    engine = create_engine('postgresql+psycopg2://', creator=conn)
    Session = sessionmaker(bind=engine)
    session = Session()
    yield session
    session.close()
```

load_database, if I can get the debugger to stop on that function, would be replaced with a sql file.

### What are the results

The function never seems to get called

### What are the expected results

The function should get called or I should be able to reset the db for every test.

**Comment by fizyk** [comment]
have you tried to put `breakpoint` in place of print?

Another thought, do you use that fixture in some test?

These are kind of the same things as tests [here](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/tests/docker/test_nooproc_docker.py), so it ought to work

**Comment by guywilsonjr** [comment]
@ahahn95 
The docs could use a little updating.
For example Notice how you're overwriting the imported fixtures _**postgresql_noproc**_ and _**postgresql**_


```
postgresql_noproc = postgresql_noproc(load=[load_database])
postgresql = postgresql("postgresql_noproc", dbname="data_retention")
```
I've figured out the fix after hours of toil It's a bit

**Comment by guywilsonjr** [comment]
So I'd recommend a change to something like this. A lot tends to feel a little fragile, but patching C-extensions isn't trivial:

```
import psycopg2
from pytest_postgresql.factories import postgresql_noproc
import pytest
from pytest_postgresql.janitor import DatabaseJanitor


def load_database(**kwargs):
    print('hi')


psql_proc = postgresql_noproc(load=[load_database])


@pytest.fixture
def get_db(psql_proc):
    """
        Given the postgresql process fixture object returns a db connection
        :param psql_proc: postgres process fixture
        :return: psycopg2 connection
        """
    janitor = DatabaseJanitor(
        psql_proc.user,
        psql_proc.host,
        psql_proc.port,
        psql_proc.dbname,
        psql_proc.version,
        psql_proc.password,
    )
    with janitor:
        conn = psycopg2.connect(
            dbname=psql_proc.dbname,
            user=psql_proc.user,
            password=psql_proc.password,

            host=psql_proc.host,
            port=psql_proc.port,
            cursor_factory=psycopg2.extras.RealDictCursor
        )
        yield conn
        
        
class TestClass:
    def test_one(self, get_db):
        pass #... do stuff
    
    def test_two(self, get_db):
        pass #... do stuff
```
