### ISSUE TITLE
Cannot start postgresql server when `pytest` is run as root

### ISSUE THREAD

**Issue by needs** [ClearcodeHQ/pytest-postgresql#455]
### What action do you want to perform

Using `pytest-postgresql` inside the [official docker python container](https://hub.docker.com/_/python).

```python
def test_postgres(postgresql):
    pass
```

### What are the results

```
E               subprocess.CalledProcessError: Command '['/usr/lib/postgresql/11/bin/pg_ctl', 'initdb', '--pgdata', '/tmp/pytest-of-root/pytest-0/pytest-postgresql-postgresql_proc_with_schema0/data-24741', '-o', '--username=postgres --auth=trust']' returned non-zero exit
 status 1.

/usr/local/lib/python3.9/subprocess.py:528: CalledProcessError
---------------------------------------------------------------------------------------------------------------------------- Captured stderr setup ----------------------------------------------------------------------------------------------------------------------------
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```

### What are the expected results

Postgresql server is launched using `pg_ctl`, and `pg_ctl` will [refuse to run as root](https://wiki.debian.org/PostgreSql#User_access).  I guess a possible fix is to add a configuration option to be able to specify which system user to use when launching postgresql.

Note that switching to a non-root user inside the official python docker container before running pytest produce a never ending stream of issues as soon as other pytest plugins are in use.

### Temporary hacky fix

Create a custom fixture to change the executable to our own script.

```python
from pytest_postgresql import factories

postgresql_proc_my = factories.postgresql_proc(executable='./pg_ctl.sh')
postgresql_my = factories.postgresql('postgresql_proc_my')

def test_postgres(postgresql_my):
    pass
```

Then create `pg_ctl.sh`:

```bash
#!/bin/bash

if [ "$2" = "--pgdata" ]; then
	# Recursively change parent directories permissions so that pg_ctl can access the necessary files as non-root.
	f=$(dirname "$3")
	while [[ $f != / ]]; do chmod o+rwx "$f"; f=$(dirname "$f"); done;
fi

# Execute pg_ctl as postgres instead of root.
sudo -u postgres "/usr/lib/postgresql/11/bin/pg_ctl" "$@"
```

You will need to install sudo using `apt-get install sudo`.

**Comment by fizyk** [comment]
@needs That's how the postgresql decided to handle itself.

Could you post a snippet out of the dockerfile?

Anyway, I suppose you base your dockerfile on the official python image, right? If so, please add a user and switch to the new user first thing after you install what you need there.

https://docs.docker.com/engine/reference/builder/#user

You won't run your code as a root on production anyway?

**Comment by needs** [comment]
> Could you post a snippet out of the dockerfile?

Here is the curated Dockerfile (without the necessary changes for the temporary fix):

```Dockerfile
FROM python:3 AS base
RUN apt-get update && apt-get install -y postgresql
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "pytest", "--cov", "--cov-report", "term-missing" ]
```

> Anyway, I suppose you base your dockerfile on the official python image, right?

Yes.

> If so, please add a user and switch to the new user first thing after you install what you need there.

It works, with some tweaks but it works.  Here is the modified Dockerfile.  Due to the fact that pytest is now installed by the new user, the pytest binary is now in `/home/test/.local/bin` and as such is not in $PATH.  One way to fix this issue is to use `python -m pytest`.

```Dockerfile
FROM python:3 AS base
RUN useradd --create-home --shell /bin/bash test && apt-get update && apt-get install -y postgresql
USER test
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "python", "-m", "pytest", "--cov=.", "--cov-report", "term-missing" ]
```

> You won't run your code as a root on production anyway?

I would not, but the use case here was to run tests inside an isolated container.  So being root wasn't really an issue security-wise.

Anyway, with this new Dockerfile the temporary fix is not needed anymore and my tests can use postgres.  Thanks !

**Comment by zhangchi1** [comment]
Hi @needs @fizyk, we are facing a similar issue with the following message
```
E               subprocess.CalledProcessError: Command '['/usr/lib/postgresql/11/bin/pg_ctl', 'initdb', '--pgdata', '/tmp/pytest-of-root/pytest-0/pytest-postgresql-postgresql_my_proc0/data-20661', '-o', '--username=postgres --auth=trust']' returned non-zero exit status 1.
/usr/local/lib/python3.7/subprocess.py:512: CalledProcessError
---------------------------- Captured stderr setup -----------------------------
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
``` 
The only difference is that we are using python:3.7 as base image in our CI job. 
We have tried:  
```
    - su -
    - apt-get install sudo -y
    - sudo -u postgres bash
```
But still, getting the same error msg, wondering if you have any suggestions? Thanks a lot,

**Comment by needs** [comment]
> But still, getting the same error msg, wondering if you have any suggestions? Thanks a lot,

Two straightforward possibilities: 

1. Launch postgres as a non-root user.
2. Connect to an external postgres server.  

Even though I initially solved this issue by using a non-root user, I now use the [official postgres](https://hub.docker.com/_/postgres) container.

**Comment by fizyk** [comment]
@zhangchi1 what @needs wrote.

After you install all your system dependencies, create and switch new user and run your process as this user
