### ISSUE TITLE
Using freezetime with postgresql

### ISSUE THREAD

**Issue by vskr** [ClearcodeHQ/pytest-postgresql#456]
### What action do you want to perform

Ability to freeze and / or advance time using pytest-postgresql

Is it possible to advance time using pytest-postgresql. I tried using freezetime but I don't think it works as freezetime only mocks datetime in python but not on the database (e.g. if we have a column TIME in a table that doesn't advance using freezetime).

If there is a user error on my part and if it is indeed possible to use freezetime. Please let me know.

Thanks for the library. It has been very useful.

### What are the expected results

**Comment by fizyk** [comment]
No I'm not aware of such functionality, Postgresql is a separate process you're working with in tests (and application).

you'd either have to use delteas to dance around current time in a conscious manner OR fill in the time column manually based on your mocking requirements. 
It can be apart of the data fixture, and no matter if you're using ORMs or raw SQL, you should be able to fill in these columns even, if you define them as auto update with current time.
