### ISSUE TITLE
postgresql_noproc with pytest-xdist and each worker using a separate database in the shared process

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/pytest-postgresql#470]
### What action do you want to perform

I want to run a larger test suite using pytest-postgresql with the `postgresql_noproc` fixture (so all tests use PostgreSQL in a single Docker container) in parallel with pytest-xdist.

### What are the results

It fails due to all test processes attempting to concurrently create or drop the same test database specified via `dbname`.

### What are the expected results

Tests succeed, operating on separate databases. (Similarly how with `postgresql_proc` we run separate processes for the databases.) This can be easily worked around by using the executor and `DatabaseJanitor` directly without the fixtures and passing a database name containing the value of the `worker_id` fixture.

I have two ideas how this can be implemented:

* either support a fixture for overriding the `dbname` parameter (so the user could provide a session-scoped fixture using `worker_id`),
* or detect xdist and adjust database names: but this might be too fragile to not break other use cases.

In any case, this still needs support for overriding `dbname` or just making it unique: in my test suite a single worker might mix tests using different database templates (one has tables used by tests and the other one is used for testing migrations on an empty database).

**Comment by fizyk** [comment]
Okay, so basically the noprocess would have to be able to somehow differ the dbname depending on the presence/usage of the xdist or not. to actually separate parallel test runs

**Comment by mmaslowskicc** [comment]
Yes. It would be sufficient to special case xdist workers which can be detected like in <https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/plugin.py#L253> (so we wouldn't depend on pytest-xdist).

So maybe a simpler change: if running in an xdist worker, append e.g. `_gw1` to the database name if using a noop executor. This breaks tests that run with xdist, hardcode the database name but have no overlapping runs of multiple tests using PostgreSQL.

**Comment by tl24** [comment]
I would be interested in this as well
