### ISSUE TITLE
I get a connection is already closed error during my tests

### ISSUE THREAD

**Issue by multisme** [ClearcodeHQ/pytest-postgresql#492]
### What action do you want to perform
I'm trying to run tests with pytest-postgresql
For this i pass a session object to my crud function.

### What are the results
The connection get dropped after a commit or a refresh and i get the error 
`sqlalchemy.exc.InterfaceError: (psycopg2.InterfaceError) connection already closed
`

### What are the expected results
I believe should be able to reuse the db_session object?

**Comment by rafmagns-skepa-dreag** [comment]
@multisme what was your issue? I'm running into something similar and think it may be the OOM killer inside a container but I'm not quite sure yet

**Comment by fizyk** [comment]
@rafmagns-skepa-dreag I have a feeling that I answered similar issue here or maybe on pytest-mysql... 

Could you show me some basic test example that could reproduce the issue?

**Comment by rafmagns-skepa-dreag** [comment]
it's unfortunately not reproducible from our testing so I can't provide an example, but I appreciate you checking in
