### ISSUE TITLE
Unable to connect to Postgresql in a docker

### ISSUE THREAD

**Issue by igondiu** [ClearcodeHQ/pytest-postgresql#540]
### What action do you want to perform
Connect to a postgresql db in a docker container

### What are the results
I copied the example from the README.md:
```python
postgresql_in_docker = factories.postgresql_noproc()
postresql = factories.postgresql("postgresql_in_docker", db_name="test")


def test_postgres_docker(postresql):
    """Run test."""
    cur = postgresql.cursor()
    cur.execute("CREATE TABLE test (id serial PRIMARY KEY, num integer, data varchar);")
    postgresql.commit()
    cur.close()
```

First of all, there are 2 mistakes in this example, the first one is the name of the fixture which has to be postgresql instead of postresql,
the second mistake is the argument db_name which has to be dbname.

After I made the changes and the code is syntactically correct and compiles, I got the error:
AttributeError: 'function' object has no attribute 'cursor'

### What are the expected results
Get a cursor and use it to insert some data in the database in the docker container

**Comment by mmaslowskicc** [comment]
I get this error only when `postgresql` (from `postgresql.cursor()`) is the fixture name but not the function parameter. The test works when I fix both fixture names.
