### ISSUE TITLE
Using postgresql_noproc in a different files

### ISSUE THREAD

**Issue by tassadar81** [ClearcodeHQ/pytest-postgresql#680]
### What action do you want to perform
define this fixture in two separate files containing one test each using it
postgresql_noproc = factories.postgresql_noproc(
    load=["whatever.sql"],
    dbname="tests"
)

postgresql = factories.postgresql(
    "postgresql_noproc",
    dbname="tests"
)

run a common postgres in a docker container;

### What are the results
self = <psycopg.Cursor [closed] [BAD] at 0x7fe15841df40>, query = 'CREATE DATABASE "tests_tmpl";', params = None

    def execute(
        self: _Self,
        query: Query,
        params: Optional[Params] = None,
        *,
        prepare: Optional[bool] = None,
        binary: Optional[bool] = None,
    ) -> _Self:
        """
        Execute a query or command to the database.
        """
        try:
            with self._conn.lock:
                self._conn.wait(
                    self._execute_gen(query, params, prepare=prepare, binary=binary)
                )
        except e.Error as ex:
>           raise ex.with_traceback(None)
E           psycopg.errors.DuplicateDatabase: database "tests_tmpl" already exists

/usr/local/lib/python3.9/dist-packages/psycopg/cursor.py:725: DuplicateDatabase

### What are the expected results
That test doesn't fails; it's limiting to define all the tests in a single file

**Comment by fizyk** [comment]
@tassadar81 but what exactly are you trying to do? the proc/noproc fixtures are session ones. Once that fixture starts it gets finished at the end of the test session, not earlier.

**Comment by tassadar81** [comment]
I'm writing some libs that some are accessing database and i wrote a test per class. Guess that i could create a db one per class but this doesn't optimize the performance i guess

**Comment by fizyk** [comment]
think of it that proc/noproc manages database server and creates the template once per session, and the client fixture does the cleaning and resetting of the database between tests.
Otherwise, you'd need two different databases (even if the same tests) to have it as in the first post. But unless you run tests in parallel with ie. with xdist that wouldn't be convenient.
