### ISSUE TITLE
What is the default fixture running?

### ISSUE THREAD

**Issue by stevenwong** [ClearcodeHQ/pytest-postgresql#685]
This is a question, not an issue. The documentation provides examples to connect to an existing postgres test server or an instance running in docker via `_noproc`. So then what's default `postgresql` client fixture running? Does it start its own postgresql instance via docker or something? Apologies in advance as this isn't clear from the documentation.

**Comment by fizyk** [comment]
@stevenwong no problem. The `postgresql` fixture connects by default to the postgresql instance spin up by the `postgresql_proc` fixture. And it spins it using the installed postgresql binary installed on the system.
