### ISSUE TITLE
License confusion: GPLv3 and LGPLv3 in repository

### ISSUE THREAD

**Issue by archoversight** [ClearcodeHQ/pytest-postgresql#727]
### What action do you want to perform

Move COPYING.lesser to COPYING to make it clear it's LGPL 3, and remove the GPLv3 license entirely from this repository.

### What are the results

Github shows that the project is licensed under LGPLv3 in the side-bar, and not both LGPL and GPL. This would match what is being published to PyPI

### What are the expected results

Clarifying what license the project is licensed under

**Comment by mmaslowskicc** [comment]
This is correct and as recommended by https://www.gnu.org/licenses/gpl-howto.html. LGPL3 is a supplement to GPL3 so it needs its text too.

Exact licenses are specified via license notices in each source file. As GitHub is not reading these, it cannot guess correctly if there are GPL-only files.

**Comment by fizyk** [comment]
Thanks @mmaslowskicc  
Exact same way as GNU is described at choosealincense https://choosealicense.com/licenses/lgpl-3.0/#how-to-apply 

@archoversight is there any other reason except to display the licenses consistently across pypi and github?

**Comment by archoversight** [comment]
@fizyk that was primarily the issue. When looking at Github it explicitly mentions GPLv3 which makes people twitchy about using it as part of the testing setup for internal/commercial projects and felt confusing. It seems like this is on Github to fix on their end then.

**Comment by fizyk** [comment]
![Screenshot_20230419-235201.png](https://user-images.githubusercontent.com/229393/233208148-c8a858f8-1e01-4042-babb-67c5a8f0ed22.png)

@archoversight so it might be also github UI related. Github app for Android shows explicitly lgpl

**Comment by fizyk** [comment]
But redirects on click to GPL text exclusively... 🤦‍♂️
