### ISSUE TITLE
Cannot run pytest-postgresql with psycopg[binary]

### ISSUE THREAD

**Issue by henriquemeloo** [ClearcodeHQ/pytest-postgresql#827]
I have tried running pytest-postgresql with a psycopg[binary] installation but I get a `pytest_postgresql.exceptions.ExecutableMissingException: Could not found pg_config executable. Is it in systenm $PATH?` error.

I thought the binary installation should cover all the dependencies for psycopg and pytest-postgresql to run, but pytest-postgresql can't find a necessary Postgresql file.

Reproducible example:
`Dockerfile`:
```Dockerfile
FROM python:3.11-slim

RUN pip install pytest==7.3.2 pytest-postgresql==5.0.0 psycopg[binary]==3.1.12

WORKDIR /tests
COPY test.py .

ENTRYPOINT [ "pytest", "test.py" ]
```

`test.py`:
```python
import pytest
import psycopg


@pytest.fixture(scope="function")
def db_session(postgresql):
    with psycopg.connect(
        f"postgresql+psycopg2://{postgresql.info.user}:"
        f"@{postgresql.info.host}:{postgresql.info.port}"
        f"/{postgresql.info.dbname}"
    ) as conn:
        yield conn


def test_something(db_session):
    assert True
```

Running `docker build . -t test && docker run --rm test` gives me:
```
request = <SubRequest 'postgresql_proc' for <Function test_something>>
tmp_path_factory = TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x7f844fd0fcd0>, _basetemp=None, _retention_count=3, _retention_policy='all')

    @pytest.fixture(scope="session")
    def postgresql_proc_fixture(
        request: FixtureRequest, tmp_path_factory: TempPathFactory
    ) -> Iterator[PostgreSQLExecutor]:
        """Process fixture for PostgreSQL.
    
        :param request: fixture request object
        :param tmp_path_factory: temporary path object (fixture)
        :returns: tcp executor
        """
        config = get_config(request)
        postgresql_ctl = executable or config["exec"]
        pg_dbname = dbname or config["dbname"]
        pg_load = load or config["load"]
    
        # check if that executable exists, as it's no on system PATH
        # only replace if executable isn't passed manually
        if not os.path.exists(postgresql_ctl) and executable is None:
            try:
                pg_bindir = subprocess.check_output(
                    ["pg_config", "--bindir"], universal_newlines=True
                ).strip()
            except FileNotFoundError as ex:
>               raise ExecutableMissingException(
                    "Could not found pg_config executable. Is it in systenm $PATH?"
                ) from ex
E               pytest_postgresql.exceptions.ExecutableMissingException: Could not found pg_config executable. Is it in systenm $PATH?

/usr/local/lib/python3.11/site-packages/pytest_postgresql/factories/process.py:104: ExecutableMissingException
=========================== short test summary info ============================
ERROR test.py::test_something - pytest_postgresql.exceptions.ExecutableMissin...
=============================== 1 error in 0.16s ===============================
```

**Comment by fizyk** [comment]
@henriquemeloo psycopg[binary] only installs already compiled version of psycopg, but the default fixtures for pytest-postgresql start PostgreSQL process to connect to, and they need something to start.

Where do you intend to keep your PostgreSQL in tests? Is it a docker-compose or something?

**Comment by henriquemeloo** [comment]
> @henriquemeloo psycopg[binary] only installs already compiled version of psycopg, but the default fixtures for pytest-postgresql start PostgreSQL process to connect to, and they need something to start.
> 
> Where do you intend to keep your PostgreSQL in tests? Is it a docker-compose or something?

Oh, ok. So pytest-postgresql still needs a running instance of PostgreSQL? It wasn't clear to me. I thought maybe it would be mocking most of Postgres. In this case, I would run the database in a separate container, with a compose file. I have just attempted this, but I still get the "ExecutableMissingException: Could not found pg_config executable." error.

Here is the `docker-compose.yml` file:
```yml
services:
  test:
    build: .

  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=postgres
```

The Dockerfile:
```Dockerfile
FROM python:3.11-slim

RUN pip install pytest==7.3.2 pytest-postgresql==5.0.0 psycopg[binary]==3.1.12 sqlalchemy==2.0.22

WORKDIR /tests
COPY test.py .

ENTRYPOINT [ "pytest", "test.py" ]
```

And `test.py`:
```python
import psycopg
import pytest

@pytest.fixture(scope="function")
def db_session(postgresql):
    with psycopg.connect(
        "postgresql+psycopg2://postgres:postgres"
        "@postgres:5432"
        "/postgres"
    ) as conn:
        yield conn

def test_something(db_session):
    assert True
```

**Comment by fizyk** [comment]
@henriquemeloo take a look at these tests:

https://github.com/ClearcodeHQ/pytest-postgresql/blob/main/tests/docker/test_noproc_docker.py

You'd need to do a bit more configuration in your conftests then, but that should be perfectly doable. These fixtures do not run pg_config, or start PostgreSQL service.

basically, you'll need noop_executor and point PostgreSQL fixture factory to that executor.

You can even overshadow fixtures delivered by the plugin, so you won't accidentally include fixture trying to run pg_config

A brief readme paragraph: https://github.com/ClearcodeHQ/pytest-postgresql#connecting-to-already-existing-postgresql-database

**Comment by fizyk** [comment]
oh, right, there's more: https://github.com/ClearcodeHQ/pytest-postgresql#connecting-to-postgresql-in-a-docker

**Comment by henriquemeloo** [comment]
Thank you! This works:
`docker-compose.yml`:
```yml
services:
  test:
    build: .

  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=postgres
```
`Dockerfile`:
```Dockerfile
FROM python:3.11-slim

RUN pip install pytest==7.3.2 pytest-postgresql==5.0.0 psycopg[binary]==3.1.12 sqlalchemy==2.0.22

WORKDIR /tests
COPY test.py .

ENTRYPOINT [ "pytest", "test.py" ]
```
`test.py`:
```python
import pytest_postgresql.factories.client
import pytest_postgresql.factories.noprocess


postgresql_no_proc = pytest_postgresql.factories.postgresql_noproc(
    host="postgres", password="postgres"
)
postgres_client = pytest_postgresql.factories.client.postgresql(
    "postgresql_no_proc"
)


def test_something(postgres_client):
    cur = postgres_client.cursor()
    cur.execute("CREATE TABLE test (id serial PRIMARY KEY, num integer, data varchar);")
    postgres_client.commit()
    cur.close()
```
