### ISSUE TITLE
Compatibility with pytest 8.0.0

### ISSUE THREAD

**Issue by zx80** [ClearcodeHQ/pytest-postgresql#880]
### What action do you want to perform

I want to run old tests with `pytest` 8.0.0 released _yesterday_ and `pytest-postgresql` 5.0.0.

### What are the results

These tests are now broken while running the fixture:

```
>               for load_element in pg_load:
E               TypeError: 'NoneType' object is not iterable

venv/lib/python3.12/site-packages/pytest_postgresql/factories/process.py:147: TypeError
```

### What are the expected results

That it would work?

The question is to know whether `pytest-postgresql` works properly with `pytest` 8.0.0.

**Comment by fizyk** [comment]
That's fixed in 5.1.0 already :)
