### ISSUE TITLE
Tests hung if logging_collector is on in postgresql.conf

### ISSUE THREAD

**Issue by brainmorsel** [ClearcodeHQ/pytest-postgresql#90]
In official postgresql RPMs for Centos 7 logging_collector enabled by default (in `/usr/pgsql-9.6/share/postgresql.conf.sample`) and will catch all output to stderr.

`wait_for_postgres()` will wait for message `'database system is ready to accept connections'` forever.

As workaround you can disable logging_collector manually:
```py
# conftest.py
from pytest_postgresql import factories
postgresql_proc = factories.postgresql_proc(startparams='-o "-c logging_collector=off"')
```

**Comment by fizyk** [comment]
@brainmorsel please check version 1.3.1
