### ISSUE TITLE
Template database stuck in a state of not allowing connections

### ISSUE THREAD

**Issue by Vladimir-Filimonov** [ClearcodeHQ/pytest-postgresql#914]
### What action do you want to perform
Running standalone PG in a docker.
I want to run test that create new database using template database.

### What are the results
New database created (and dropped after tests execution). However template database is stuck in a state of not allowing connections. 

> [55000] FATAL: database "my_test_template" is not currently accepting connections

Because of this: https://github.com/ClearcodeHQ/pytest-postgresql/blob/main/pytest_postgresql/janitor.py#L75
Code never allows connections again after creating database out of the template

### What are the expected results
There is eventual possibility to connect to a template database when tests are not running. 

### Possible solution
```python
    # Define new static method
    @staticmethod
    def _datallowconn(cur: Cursor, dbname: str) -> None:
        cur.execute(f'ALTER DATABASE "{dbname}" with allow_connections true;')

    # Add calling to new method after creation of a database (see very last line)
    def init(self) -> None:
        """Create database in postgresql."""
        with self.cursor() as cur:
            if self.is_template():
                cur.execute(f'CREATE DATABASE "{self.template_dbname}";')
            elif self.template_dbname is None:
                cur.execute(f'CREATE DATABASE "{self.dbname}";')
            else:
                # All template database does not allow connection:
                self._dont_datallowconn(cur, self.template_dbname)
                # And make sure no-one is left connected to the template database.
                # Otherwise, Creating database from template will fail
                self._terminate_connection(cur, self.template_dbname)
                cur.execute(f'CREATE DATABASE "{self.dbname}" TEMPLATE "{self.template_dbname}";')

               # ----- Call new method here ------ #
                self._datallowconn(cur, self.template_dbname)

```

**Comment by fizyk** [comment]
@Vladimir-Filimonov Why do you want to connect to the template database?

**Comment by Vladimir-Filimonov** [comment]
my template database is database that maintained by migrations. for running tests I create new database out of template and run tests on it. So as a developer iterating on new database changes and new tests I want to be able to see content of template database.
I general I think its a fair ask to be able to browse through template database when tests are not running. It looks a bit strange to lock it down once and forever

**Comment by fizyk** [comment]
Hmmm....

Okay, then I'd have to tinker around with https://www.postgresql.org/docs/current/manage-ag-templatedbs.html datistemplate and without disallowing connections to the database. It works same way throughout supported postgres version 12-16 so if it works there would not be needed any special handling depending on versions 🤔

**Comment by fizyk** [comment]
Someone attempted this in #904 however any signal from there that it's something more than initial playing around 🤔
