### ISSUE TITLE
Request: officially supporting Python 3.12

### ISSUE THREAD

**Issue by jamesbraza** [ClearcodeHQ/pytest-postgresql#915]
### What action do you want to perform

It would be nice to add 3.12 to the `README.rst` badge and PyPI classifiers in `pyproject.toml`.

Python 3.12 is already in GitHub Actions test matrices (and tests are passing on `main`), so it should work.

### What are the results

Officially supporting Python 3.12

**Comment by fizyk** [comment]
Oh, that's a mistake on my part. Sorry

**Comment by fizyk** [comment]
5.1.1 has the missing classifier, nothing else changed since 5.1.0

**Comment by jamesbraza** [comment]
Nice, thank you @fizyk ! Don't forget the `README.rst` badge too, if you got a sec

<img width="190" alt="screenshot of current README badge" src="https://github.com/ClearcodeHQ/pytest-postgresql/assets/8990777/86e5ecdb-be34-4883-85fd-24ecaff99d0e">

**Comment by fizyk** [comment]
@jamesbraza that's automatic based on pypi, so it just needs to refresh cache
