### ISSUE TITLE
modulenotfounderror while using load in factory

### ISSUE THREAD

**Issue by GFuhr** [ClearcodeHQ/pytest-postgresql#918]
### What action do you want to perform
When I try to load an sql file through the load argument of the factory : 
`postgresql_in_docker = factories.postgresql_noproc(user = DBConfig().user, password=DBConfig().password)
postgresql_mok = factories.postgresql("postgresql_in_docker",
                                       dbname="mydb", load=["test_base.sql", ])
`
I get this error : 

> ERROR tests/test_decorators.py::test_decorator_fk_table_not_exists - ModuleNotFoundError: No module named 'test_base'

However if I write : 
`postgresql_in_docker = factories.postgresql_noproc(user = DBConfig().user, password=DBConfig().password)
postgresql_mok = factories.postgresql("postgresql_in_docker",
                                       dbname="mydb", load=["./test_base.sql", ])
`
Note the **./** in front of the filename, in that case everything works well

I just upgraded my version to 5.1.1 and the issue is still there.

G.

**Comment by fizyk** [comment]
@GFuhr the issue is solved on master.
I'll probably release the new functionality version next week, depending on the time if it'll let me. (I think the minimum would be for me to attempt to address #914

**Comment by fizyk** [comment]
@GFuhr check version 6.0.0. Mind that paths will now have to be pathlib.Path instances
