### ISSUE TITLE
support `\` in linux temporary path

### ISSUE THREAD

**Issue by bhelgs** [ClearcodeHQ/pytest-postgresql#982]
### What action do you want to perform
By default pytest temporary paths on AWS workspaces will contain a `\` in the temporary path due to [their username conventions](https://docs.aws.amazon.com/workspaces/latest/adminguide/manage_linux_workspace.html).

Maybe you might want to support `\` in paths?
Some additional command quotes seem fix the `\` issue and may help with other special linux path characters.

### What are the results
Temporary data is generated under `/tmp/ACTIVEDIRECTORY`**\\**`user.name/pytest-101/pytest-postgresql-postgresql_proc0/` but **some** commands lost the `\`

### What are the expected results
I was able to run without issue after quoting the paths in `PostgreSQLExecutor.BASE_PROC_START_COMMAND` and `PostgreSQLExecutor.running()`

### Workaround
set `--basetemp=` argument in pytest command

**Comment by bhelgs** [comment]
Thank you very much for creating such a great project! 🏆 
Please let me know if you would like for me to open a couple line PR.

**Comment by fizyk** [comment]
@bhelgs if you're able to probide PR with fix (and test preferably), please go ahead :)
